// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkxyTDb_u4D4jK-4es-UBOxBRKSA07N8o',
    appId: '1:367238386486:android:0f53472fc27332b9a49997',
    messagingSenderId: '367238386486',
    projectId: 'sefirot-ff9af',
    storageBucket: 'sefirot-ff9af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO8fcuxj3KMwVGxW4Zhe3Ka5cD_uHDaR8',
    appId: '1:367238386486:ios:450adfe09b657ab4a49997',
    messagingSenderId: '367238386486',
    projectId: 'sefirot-ff9af',
    storageBucket: 'sefirot-ff9af.firebasestorage.app',
    iosBundleId: 'com.example.sefirot',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_2NDMLdIZ-Fr8eA9JxjyjcrPHFVBMQF4',
    appId: '1:367238386486:web:9a80f03b8bd9f0b5a49997',
    messagingSenderId: '367238386486',
    projectId: 'sefirot-ff9af',
    authDomain: 'app.pelegrin.cloud',
    storageBucket: 'sefirot-ff9af.firebasestorage.app',
    measurementId: 'G-0GHP5XFD6R',
  );

}
