const List<String> globalLanguages = [
  'Afrikaans',
  'Amharic (አማርኛ)',
  'Azerbaijani (Azərbaycan)',
  'Bengali (বাংলা)',
  'Bhojpuri (भोजपुरी)',
  'Burmese (မြန်မာစာ)',
  'Cebuano (Bisaya)',
  'Chittagonian (চাটগাঁইয়া)',
  'Egyptian Arabic (مصرى)',
  'English',
  'Farsi (فارسی)',
  'French (Français)',
  'Fulah (Fulfulde)',
  'Gan Chinese (赣语)',
  'German (Deutsch)',
  'Gujarati (ગુજરાતી)',
  'Hakka Chinese (客家话)',
  'Hausa (هَوُسَ)',
  'Hindi (हिन्दी)',
  'Hmong (Hmoob)',
  'Igbo (Asụsụ Igbo)',
  'Indonesian (Bahasa Indonesia)',
  'Italian (Italiano)',
  'Japanese (日本語)',
  'Javanese (Basa Jawa)',
  'Jin Chinese (晋语)',
  'Kannada (ಕನ್ನಡ)',
  'Khmer (ភាសាខ្មែរ)',
  'Korean (한국어)',
  'Kurdish (Kurmanji)',
  'Malagasy',
  'Malay (Bahasa Melayu)',
  'Malayalam (മലയാളം)',
  'Mandarin Chinese (普通话)',
  'Marathi (मराठी)',
  'Nepali (नेपाली)',
  'Nigerian Pidgin',
  'Northern Min (闽北语)',
  'Oriya (ଓଡ଼ିଆ)',
  'Oromo (Afaan Oromoo)',
  'Pashto (پښتو)',
  'Polish (Polski)',
  'Portuguese (Português)',
  'Punjabi (ਪੰਜਾਬੀ)',
  'Quechua (Runa Simi)',
  'Russian (Русский)',
  'Serbo-Croatian (Srpskohrvatski)',
  'Shona (chiShona)',
  'Silesian (Ślōnskiy)',
  'Sindhi (سنڌي)',
  'Sinhalese (සිංහල)',
  'Somali (Soomaaliga)',
  'Southern Min (闽南语)',
  'Spanish (Español)',
  'Standard Arabic (العربية)',
  'Sundanese (Basa Sunda)',
  'Swahili (Kiswahili)',
  'Tagalog',
  'Tamil (தமிழ்)',
  'Telugu (తెలుగు)',
  'Thai (ไทย)',
  'Turkish (Türkçe)',
  'Ukrainian (Українська)',
  'Urdu (اردو)',
  'Uzbek (Oʻzbekcha)',
  'Vietnamese (Tiếng Việt)',
  'Wu Chinese (吴语)',
  'Xiang Chinese (湘语)',
  'Yoruba (Yorùbá)',
  'Yue Chinese (粵語)',
  'Zulu (isiZulu)',
];
