const List<String> globalLanguages = [
  'Afrikaans',
  'Amharic',
  'Azerbaijani',
  'Bengali',
  'Bhojpuri',
  'Burmese',
  'Cebuano',
  'Chittagonian',
  'Egyptian Arabic',
  'English',
  'Farsi (Persian)',
  'French',
  'Fulah (Fulfulde)',
  'Gan Chinese',
  'German',
  'Gujarati',
  'Hakka Chinese',
  'Hausa',
  'Hindi',
  'Hmong',
  'Igbo',
  'Indonesian',
  'Italian',
  'Japanese',
  'Javanese',
  'Jin Chinese',
  'Kannada',
  'Khmer',
  'Korean',
  'Kurdish (Kurmanji)',
  'Malagasy',
  'Malay (Bahasa Melayu)',
  'Malayalam',
  'Mandarin Chinese',
  'Marathi',
  'Nepali',
  'Nigerian Pidgin',
  'Northern Min',
  'Oriya (Odia)',
  'Oromo',
  'Pashto',
  'Polish',
  'Portuguese',
  'Punjabi (Western)',
  'Quechua',
  'Russian',
  'Serbo-Croatian',
  'Shona',
  'Silesian',
  'Sindhi',
  'Sinhalese',
  'Somali',
  'Southern Min (Min Nan)',
  'Spanish',
  'Standard Arabic',
  'Sundanese',
  'Swahili',
  'Tagalog',
  'Tamil',
  'Telugu',
  'Thai',
  'Turkish',
  'Ukrainian',
  'Urdu',
  'Uzbek',
  'Vietnamese',
  'Wu Chinese (Shanghainese)',
  'Xiang Chinese',
  'Yoruba',
  'Yue Chinese (Cantonese)',
  'Zulu',
];
